apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx-server
        image: stenote/nginx-hostname:latest
        ports:
        - containerPort: 8080